#ifndef CHICHI_BASE_H
#define CHICHI_BASE_H

    #define CC_BASE_VERSION_MAJOR 1
    #define CC_BASE_VERSION_MINOR 0
    #define CC_BASE_VERSION_PATCH 0
    #define CC_BASE_VERSION ((CC_BASE_VERSION_MAJOR * 10000) + (CC_BASE_VERSION_MINOR * 100) + CC_BASE_VERSION_PATCH)

    #define CC_STRINGIFY_IMPLEMENTATION(x) #x
    #define CC_STRINGIFY(x) CC_STRINGIFY_IMPLEMENTATION(x)

#endif
